### ISSUE TITLE
If a recipe has been requested and fails, a notification should be sent to requestor

### ISSUE THREAD

**Issue by Popolechien** [openzim/zimfarm#516] opened 2020-07-17 14:58 UTC
It has happened to me that I request a recipe and forget about it, only to realize days later that it actually failed. 

It would be nice to have some sort of notification somewhere (email or Slack or within the farm, whichever is easiest). To be clear: not a fail notification for every fail, but just the ones that have been expressly requested.

**Comment by rgaudin** [comment] 2020-07-17 15:00
Duplicate of #277

**Closed by rgaudin** 2020-07-17 15:00 UTC
Labels: enhancement
