### ISSUE TITLE
Allow for upload of logos and banners

### ISSUE THREAD

**Issue by Popolechien** [openzim/zimfarm#564] opened 2020-11-27 13:33 UTC
The current setup when creating a recipe forces us to give a link to an online resource where the logo or banner we want to use is stored. An alternative would be able to upload these images.

**Comment by rgaudin** [comment] 2020-11-27 13:34
Duplicate of #552

**Comment by rgaudin** [comment] 2020-11-27 13:35
Duplicate of #552

**Closed by rgaudin** 2020-11-27 13:35 UTC
Labels: enhancement
