### ISSUE TITLE
High error rate this week

### ISSUE THREAD

**Issue by rgaudin** [openzim/zimfarm#848] opened 2023-10-23 10:37 UTC
[dashboard](https://kiwixorg.grafana.net/d/d2803d94-7c40-4338-bf80-f3cd7cd796bf/zimfarms?orgId=1&from=now-7d&to=now) shows 111 tasks failed out of 126 (**88%**) in the last 7d.

We should take a quick look at whether this is zimfarm related or not.

**Comment by benoit74** [comment] 2023-10-24 12:33
Duplicate of #849 finally.

**Closed by benoit74** 2023-10-24 12:33 UTC
Labels: bug, question
