### ISSUE TITLE
ZIM upload is still not always working file

### ISSUE THREAD

**Issue by kelson42** [openzim/zimfarm#399] opened 2020-02-04 06:38 UTC
See for example https://farm.openzim.org/pipeline/5e316f8dba3b9910fb870fc5

The ZIM which failed to upload is far too small.

The log is not available at https://logs.warehouse.farm.openzim.org/9940197e468703fe8cfd5b1e1032d373d080ae265268c56889793cf5d92d5b0b-json.log

**Comment by rgaudin** [comment] 2020-02-04 07:41
The ZIM file has been uploaded

```
-rw-r--r-- 1 999 users 9.8G Feb  3 02:49 /data/zimfarm-warehouse/zim/wikipedia/wikipedia_fr_all_maxi_2020-02.zim
```

From the worker log, the problem is:

* upload started
* scraper completed (that's the status we're seeing)
* worker is stuck waiting for the scraper log to finish upload
* so it can't move on to updating ZIM file upload status
* not update task status to `succeeded`

The scraper log upload did complete but for some reason, the container is still running

```
zimfarm logs 70fc5_logup_9940197e468703fe8cfd5b1e1032d373d080ae265268c56889793cf5d92d5b0b-json.log
[2020-02-02 13:56:01,330: INFO] Starting upload of /data/9940197e468703fe8cfd5b1e1032d373d080ae265268c56889793cf5d92d5b0b-json.log to sftp://uploader@warehouse.farm.openzim.org:1522/logs/9940197e468703fe8cfd5b1e1032d373d080ae265268c56889793cf5d92d5b0b-json.log
[2020-02-02 13:56:01,332: INFO] Executing: /usr/bin/sftp -i /etc/ssh/keys/zimfarm -b /tmp/tmpb_4e0h7g.txt -o GlobalKnownHostsFile /etc/ssh/known_hosts sftp://uploader@warehouse.farm.openzim.org:1522/logs/
[2020-02-02 13:56:03,750: INFO] Executing: /usr/bin/sftp -i /etc/ssh/keys/zimfarm -b /tmp/tmpikoeupjr.txt -o GlobalKnownHostsFile /etc/ssh/known_hosts -c aes128-ctr -C sftp://uploader@warehouse.farm.openzim.org:1522/logs/
[2020-02-02 13:56:08,166: INFO] Uploader ran successfuly.
[2020-02-02 13:56:08,167: INFO] [stats] uploaded 2.7 KiB in 4.42 seconds (625.3381965717339 bytes/s)
```

I'm closing this issue as the problem is different.

Regarding your second point, see #374. I manually chmod so you should be able to download it now.

**Closed by rgaudin** 2020-02-04 07:41 UTC
Labels: bug
