### ISSUE TITLE
pipeline/filter-failed does not display "last run" info anymore

### ISSUE THREAD

**Issue by kelson42** [openzim/zimfarm#542] opened 2020-10-14 10:32 UTC
It seems this is because a recipe has been renamed (`katabiblon`?) and then it breaks everything.

**Comment by rgaudin** [comment] 2020-12-16 15:07
Was actually fixed in ef25f58c8 but issue was not linked properly.

**Comment by rgaudin** [comment] 2020-12-16 15:09
For the record, the problem is indeed if a schedule has been renamed, it couldn't fetch status of its last task and failed due to incorrect schedule name.
Reopening as a delete schedule (although very rare) would raise the same.

**Closed** 2020-12-16 16:01 UTC
Labels: bug, good first issue
